[package]
name = "polkadot-statement-distribution"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Statement Distribution Subsystem"
edition = "2018"

[dependencies]
futures = "0.3.12"
tracing = "0.1.25"
polkadot-primitives = { path = "../../../primitives" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "state-trace-rpc" }
polkadot-subsystem = { package = "polkadot-node-subsystem", path = "../../subsystem" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-network-protocol = { path = "../../network/protocol" }
arrayvec = "0.5.2"
indexmap = "1.6.1"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
assert_matches = "1.4.0"
sp-keyring = { git = "https://github.com/paritytech/substrate", branch = "state-trace-rpc" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "state-trace-rpc" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", branch = "state-trace-rpc" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "state-trace-rpc" }
sc-keystore = { git = "https://github.com/paritytech/substrate", branch = "state-trace-rpc" }
