[package]
name = "polkadot-service"
version = "0.6.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parking_lot = "0.9.0"
lazy_static = "1.0"
log = "0.4.6"
futures = "0.1"
exit-future = "0.1"
slog = "^2"
hex-literal = "0.2"
av_store = { package = "polkadot-availability-store", path = "../availability-store" }
consensus = { package = "polkadot-validation", path = "../validation" }
polkadot-primitives = { path = "../primitives" }
polkadot-runtime = { path = "../runtime" }
polkadot-executor = { path = "../executor" }
polkadot-network = { path = "../network"  }
sr-io = { git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
sr-primitives = { git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
primitives = { package = "substrate-primitives", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
client-db = { package = "substrate-client-db", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
substrate-executor = { git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
substrate-network = { git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
consensus_common = { package = "substrate-consensus-common", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
grandpa = { package = "substrate-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
grandpa_primitives = { package = "substrate-finality-grandpa-primitives", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
service = { package = "substrate-service", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
telemetry = { package = "substrate-telemetry", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
substrate-keystore = { git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
srml-babe = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-generic-weight-stuff" }
srml-staking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-generic-weight-stuff" }
im-online = { package = "srml-im-online", git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-generic-weight-stuff" }
authority-discovery = { package = "substrate-authority-discovery", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
babe = { package = "substrate-consensus-babe", git = "https://github.com/paritytech/substrate", branch = "kiz-generic-weight-stuff" }
babe-primitives = { package = "substrate-consensus-babe-primitives", git = "https://github.com/paritytech/substrate", default-features = false, branch = "kiz-generic-weight-stuff" }
