[package]
name = "test-parachains"
version = "0.7.22"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Integration tests using the test-parachains"
edition = "2018"

[dependencies]
tiny-keccak = "1.5.0"
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false, features = ["derive"] }

parachain = { package = "polkadot-parachain", path = ".." }
adder = { package = "test-parachain-adder", path = "adder" }
halt = { package = "test-parachain-halt", path = "halt" }

[dev-dependencies]
sp-core = { git = "https://github.com/insipx/substrate", branch = "insipx/testing-0.8.25" }

[features]
default = [ "std" ]
std = [
	"adder/std",
	"halt/std",
]
