[package]
name = "polkadot-node-core-provisioner"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bitvec = { version = "0.17.4", default-features = false, features = ["alloc"] }
futures = "0.3.5"
log = "0.4.11"
thiserror = "1.0.21"
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }

[dev-dependencies]
sp-application-crypto = { git = "https://github.com/insipx/substrate", branch = "insipx/testing-0.8.26-1" }
sp-keystore = { git = "https://github.com/insipx/substrate", branch = "insipx/testing-0.8.26-1" }
sc-keystore = { git = "https://github.com/insipx/substrate", branch = "insipx/testing-0.8.26-1" }
futures-timer = "3.0.2"
tempfile = "3.1.0"
